# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - name: Upload Test Coverage Reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: 'coverage'
        path: 'coverage/*'
    - uses: 5monkeys/cobertura-action@master
      if: always()
      with:
        path: '*/*coverage.xml'
        minimum_coverage: 0
        repo_token: ${{ secrets.GITHUB_TOKEN }}

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run zip
      run: cd src && zip ../jinrou-wakamete-analyzer.xpi * && cd ..

    - name: Upload zip
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: 'jinrou-wakamete-analyzer.xpi'
        path: 'jinrou-wakamete-analyzer.xpi'
